function bzg4 = importfile2(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  BZG4 = IMPORTFILE2(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  BZG4 = IMPORTFILE2(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  bzg4 = importfile2("C:\Users\micha\OneDrive - Instituto Tecnologico y de Estudios Superiores de Monterrey\Segundo semestre\Analisis de sistemas electromagneticos en sistemas ingenieriles\Reto\sesion 3\CSV\bz_g4.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-May-2020 12:47:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
bzg4 = readtable(filename, opts);

%% Convert to output type
bzg4 = table2array(bzg4);
end